# Generated by Django 5.0.4 on 2024-04-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
